### PR TITLE
Installation notes to assist in case of keyserver failures...

### PR DESCRIPTION
**Pull request by JESii**
Changes to clarify what's to be done in the event that there are keyserver failures,
mostly through additional notes/links to the Security page. I've had to look this up every time, and there are a number of questions around this issue.
Wasn't sure how to test the changes... be happy to do that with some help.

### CODE REVIEW

**Comment by JESii** [comment]
Sorry; No idea what's happening with the build and the broken links...

**Comment by JESii** [comment]
Not sure what's to be done here, but if you give me some pointers I'll work on it

**Comment by havenwood** [comment]
The broken links in the build aren't related to your commit. I've fixed all of them except a Vimeo 403 that actually works outside the Nanoc check. Unfortunately, Nanoc didn't add the ability to exclude domains from the external links check until a version just after what we're pinned to.

If you rebase, all but the vimeo should pass. Disregard that one until a fix is found.

Thanks for the PR!

**Comment by JESii** [comment]
OK; I did a fetch/merge into my local repo, pushed to my fork, then clicked the "Merge remote tracking branch link below .your comment and it said it worked... hope I did that correctly

**Comment by JESii** [comment]
Sorry; not sure how to 'disregard' that error...

**Pull request closed without merging**
