### PR TITLE
Update vagrant.md

### PR DESCRIPTION
**Pull request by bogdanvlviv**
When rvm installed for Multi-User, we should run rvm script `/etc/profile.d/rvm.sh`

### CODE REVIEW

**Comment by bogdanvlviv** [comment]
@mpapis please reiview!

**Comment by bogdanvlviv** [comment]
tests failed because of broken links, same as was #292.

**Comment by mpapis** [comment]
please check tomorrow if the deploy worked - and let me know if it did not (https://www.rvm.io is uncashed) - I can look into it if there are any problems

**Comment by bogdanvlviv** [comment]
ok

**Pull request merged**
