### PR TITLE
use ruby 2.2.3

### PR DESCRIPTION
**Pull request by digitalfrost**

### CODE REVIEW

**Comment by digitalfrost** [comment]
Hi the travis build fails becaue of this

```
[ ERROR ] external_links - broken reference to http://blip.tv/akitaonrails/railsconf-2010-wayne-e-seguin-3785213: execution expired
  public/packages/zlib/index.html:
```
This is actually a dead link I will try fixing this in another pull request.

**Comment by digitalfrost** [comment]
Build fails because of this bug #265

**Comment by digitalfrost** [comment]
Opening / Closing to retriger Travis build Coderwall seems to be back up (#273)

**Comment by digitalfrost** [comment]
Good to merge!

**Comment by mpapis** [comment]
@havenwood I think last time we were bumping ruby version the deploy broke, please let me know if there are any issues and you need help with it

**Pull request merged**
