### PR TITLE
Fix mixed content warning when using HTTPS

### PR DESCRIPTION
**Pull request by sikachu**
screen shot 2015-04-13 at 10 11 27 pm

### CODE REVIEW

**Comment by mpapis** [comment]
thank you!

**Comment by reedloden** [comment]
Protocol-relative URLs should just go away. Better to use https:// explicitly.

**Comment by jrgifford** [comment]
@reedloden not all networks allow HTTPS. I agree, but sadly we are in a broken world.

**Comment by phillipp** [comment]
@jrgifford Networks that do not allow HTTPS are dangerous and broken by default. No reason for the RVM site to work around every mess in the world.

**Comment by jrgifford** [comment]
I agree it's a mess! But we can't forget our developer peers who are stuck in institutions like those described here: https://github.com/GSA/https/issues/107

(AKA: any institution that does proxy SSL stuff.)

**Comment by mpapis** [comment]
can someone elaborate on the part why "Protocol-relative URLs should just go away"?

**Comment by reedloden** [comment]
@jrgifford Why is that a problem? Forgive me for not reading that entire issue thread, but generally, in those types of institutions, it's expected that they would have their employees install a root CA that would allow their SSL interceptor proxy the ability to inspect traffic. Browsers offer this as a way to bypass normal SSL checks as well (including pinning), so it's very well-supported.

**Comment by jrgifford** [comment]
@reedloden They tend to whitelist specific SSL sites, rather than blacklist ones. And browsers aren't the only ones that have to use rvm.io - tools like cURL and similar have to. So SSL only, while great, isn't something that we should do across the board for everything yet, not without weighing the consequences.

**Comment by phillipp** [comment]
Who is browing the rvm website with curl? Additionally, if you add a crude SSL proxy foo to your network you should expect things to break. So imho the RVM website should default to SSL-only and change back to the old version if lots of users complain (which is highly unlikely).

For me the case against SSL default is not clear enough, especially because all my websites are SSL-only and don't support connections without HTTPS (only redirecting to the HTTPS version). It's about a website, and google is HTTPS-only, too.

**Pull request merged**
